In [1]:
%pip install pygame

   ---------------------------------------- 0.0/10.8 MB ? eta -:--:--
   -------- ------------------------------- 2.4/10.8 MB 13.4 MB/s eta 0:00:01
   ------------------- -------------------- 5.2/10.8 MB 13.9 MB/s eta 0:00:01
   ------------------------- -------------- 6.8/10.8 MB 11.3 MB/s eta 0:00:01
   ------------------------------------ --- 9.7/10.8 MB 12.1 MB/s eta 0:00:01
   ---------------------------------------- 10.8/10.8 MB 12.0 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [10]:
import numpy as np

x, y = 21, 10
a = np.ones((y, x))

In [11]:
a = a * 0
a[(0, 0)] = 10.0
# a[(0, 1)] = 10.0
# a[(1, 0)] = 1.0
a

array([[10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  

In [12]:
from greedy_fix import State, Action, Reward, Value, Policy

In [13]:
reward = Reward(a)
value = Value(np.zeros((y, x)), dim=0.1)

In [14]:
"""Create random equiprobable policy"""
# p_m = np.ones((4, y, x))
# p_m = p_m * 0.25
# p_m[:, 0] = 1 / 3
# p_m[:, -1] = 1 / 3
# p_m[:, :, 0] = 1 / 3
# p_m[:, :, -1] = 1 / 3
# p_m[:, 0, 0] = 1 / 2
# p_m[:, 0, -1] = 1 / 2
# p_m[:, -1, 0] = 1 / 2
# p_m[:, -1, -1] = 1 / 2
# p_m[2, 0] = 0.0
# p_m[0, -1] = 0.0
# p_m[3, :, 0] = 0.0
# p_m[1, :, -1] = 0.0
# p_m

'Create random equiprobable policy'

In [15]:
"""Create policy go down otherwise go up"""
policy_m = np.zeros((4, y, x))
policy_m[0] = 1.0
policy_m[0, -1] = 0.0
policy_m[2, -1] = 1.0
print(policy_m)

[[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

In [16]:
policy = Policy(policy_m)

In [19]:
epochs = 1000

In [20]:
np.set_printoptions(precision=2)

for i in range(epochs):
    value.update(policy=policy, reward=reward)
    # Print value
    print(value.m)

    changed = policy.update(value=value, reward=reward)
    # Print Policy
    print(f"Epoch: {i}")
    print(f"Value:\n{value.m}")
    print("Policy:")
    print(f"{' ' * 5}Down:\n{policy.m[0]}")
    print(f"{' ' * 5}Right:\n{policy.m[1]}")
    print(f"{' ' * 5}Up:\n{policy.m[2]}")
    print(f"{' ' * 5}Left:\n{policy.m[3]}")
    print(f"Policy changes: {changed}")
    print('-' * 30)

    if changed == 0:
        break

print(f"Final Value:\n{value.m}")
print(f"Final Policy:\n{policy.m}")
print(f"Maze:\n{reward.m}")

[[1.01e+01 1.01e+00 1.01e-01 1.01e-02 1.01e-03 1.01e-04 1.01e-05 1.01e-06
  1.01e-07 1.01e-08 1.01e-09 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [1.01e+00 1.01e-01 1.01e-02 1.01e-03 1.01e-04 1.01e-05 1.01e-06 1.01e-07
  1.01e-08 1.01e-09 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [1.01e-01 1.01e-02 1.01e-03 1.01e-04 1.01e-05 1.01e-06 1.01e-07 1.01e-08
  1.01e-09 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [1.01e-02 1.01e-03 1.01e-04 1.01e-05 1.01e-06 1.01e-07 1.01e-08 1.01e-09
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [1.01e-03 1.01e-04 1.01e-05 1.01e-06 1.01e-07 1.01e-08 1.01e-09 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00
  0.00e+00 0.00e+00 0.00e+00 0.00e+00 0.00e+00]
 [1.01e-04 1.01e-05 