In [3]:
pip install -U torch


  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
  Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
  Using cached MarkupSafe-2.1.5-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ---------------------------------------- 0.0/199.4 MB ? eta -:--:--
    --------------------------------------- 2.6/199.4 MB 12.5 MB/s eta 0:00:16
    --------------------------------------- 3.7/199.4 MB 12.1 MB/s eta 0:00:17
   - -------------------------------------- 6.3/199.4 MB 9.9 MB/s eta 0:00:20
   - -------------------------------------- 9.4/199.4 MB 11.1 MB/s eta 0:00:18
   -- ------------------------------------- 12.3/199.4 MB 11.7 MB/s eta 0:00:17
   -- ------------------------------------- 14.9/199.4 MB 12.0 MB/s eta 0:00:16
   --- ------------------------------------ 16.3/199.4

In [54]:
import numpy as np
np.set_printoptions(precision=2)
np.set_printoptions(linewidth=np.inf)

visibility = 2
shape = (10, 10)
map = np.random.rand(*shape) * 100
vis_shape = map.shape
vis_shape = (vis_shape[0] + visibility * 2, vis_shape[1] + visibility * 2)
visibility_map = np.zeros(shape=vis_shape, dtype=int)
visibility_map[visibility:-visibility, visibility:-visibility] = map

In [55]:
map

array([[46.15, 60.01, 75.09, 91.13, 11.07, 52.01, 36.47, 63.54, 31.58, 75.08],
       [ 5.26, 98.21, 76.72,  5.62, 88.29, 72.76, 65.38, 24.28, 51.61,  1.26],
       [23.72, 74.17, 83.09, 45.54, 32.53, 32.59, 94.34, 80.84, 17.03, 45.11],
       [62.86, 72.14, 88.5 , 13.38, 52.82, 42.7 ,  4.22, 60.35, 35.25,  0.67],
       [69.93, 67.18,  1.9 , 33.94, 72.62,  5.04, 12.88, 89.38, 93.4 , 24.76],
       [88.19, 83.02, 79.33, 39.47, 10.3 , 16.46, 86.39, 15.94, 61.64, 19.71],
       [ 4.23, 91.06, 71.97, 75.99, 30.73, 54.22, 17.95, 25.42, 27.07, 22.25],
       [ 1.51, 82.89, 76.17, 83.08, 56.93, 27.83, 37.67, 30.72, 24.63, 71.76],
       [25.89, 55.78, 23.9 , 89.3 , 54.27, 30.5 , 74.15, 54.81, 75.07, 37.66],
       [67.12, 92.92, 32.84, 18.2 ,  1.52, 29.  , 44.78, 83.66, 84.86, 43.48]])

In [56]:
visibility_map

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0, 46, 60, 75, 91, 11, 52, 36, 63, 31, 75,  0,  0],
       [ 0,  0,  5, 98, 76,  5, 88, 72, 65, 24, 51,  1,  0,  0],
       [ 0,  0, 23, 74, 83, 45, 32, 32, 94, 80, 17, 45,  0,  0],
       [ 0,  0, 62, 72, 88, 13, 52, 42,  4, 60, 35,  0,  0,  0],
       [ 0,  0, 69, 67,  1, 33, 72,  5, 12, 89, 93, 24,  0,  0],
       [ 0,  0, 88, 83, 79, 39, 10, 16, 86, 15, 61, 19,  0,  0],
       [ 0,  0,  4, 91, 71, 75, 30, 54, 17, 25, 27, 22,  0,  0],
       [ 0,  0,  1, 82, 76, 83, 56, 27, 37, 30, 24, 71,  0,  0],
       [ 0,  0, 25, 55, 23, 89, 54, 30, 74, 54, 75, 37,  0,  0],
       [ 0,  0, 67, 92, 32, 18,  1, 29, 44, 83, 84, 43,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])

In [16]:
pos = (0, 0)
visibility = 2
a[min(pos[0] - visibility) : pos[0] + visibility + 1, pos[1] - visibility : pos[1] + visibility + 1]

array([], shape=(0, 0), dtype=float64)

In [2]:
a = a * 0
a[(0, 0)] = 10.0
# a[(0, 1)] = 10.0
# a[(1, 0)] = 1.0
a

array([[10.,  0.],
       [ 0.,  0.]])

In [3]:
from greedy_fix import State, Action, Reward, Value, Policy

In [4]:
reward = Reward(a)
value = Value(np.zeros((y, x)), dim=0.1)

In [5]:
"""Create random equiprobable policy"""
# p_m = np.ones((4, y, x))
# p_m = p_m * 0.25
# p_m[:, 0] = 1 / 3
# p_m[:, -1] = 1 / 3
# p_m[:, :, 0] = 1 / 3
# p_m[:, :, -1] = 1 / 3
# p_m[:, 0, 0] = 1 / 2
# p_m[:, 0, -1] = 1 / 2
# p_m[:, -1, 0] = 1 / 2
# p_m[:, -1, -1] = 1 / 2
# p_m[2, 0] = 0.0
# p_m[0, -1] = 0.0
# p_m[3, :, 0] = 0.0
# p_m[1, :, -1] = 0.0
# p_m

'Create random equiprobable policy'

In [6]:
"""Create policy go down otherwise go up"""
policy_m = np.zeros((4, y, x))
policy_m[0] = 1.0
policy_m[0, -1] = 0.0
policy_m[2, -1] = 1.0
print(policy_m)

[[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]


In [7]:
policy = Policy(policy_m)

In [8]:
epochs = 1000

In [9]:
np.set_printoptions(precision=2)

for i in range(epochs):
    value.update(policy=policy, reward=reward)
    # Print value
    print(value.m)

    changed = policy.update(value=value, reward=reward)
    # Print Policy
    print(f"Epoch: {i}")
    print(f"Value:\n{value.m}")
    print("Policy:")
    print(f"{' ' * 5}Down:\n{policy.m[0]}")
    print(f"{' ' * 5}Right:\n{policy.m[1]}")
    print(f"{' ' * 5}Up:\n{policy.m[2]}")
    print(f"{' ' * 5}Left:\n{policy.m[3]}")
    print(f"Policy changes: {changed}")
    print('-' * 30)

    if changed == 0:
        break

print(f"Final Value:\n{value.m}")
print(f"Final Policy:\n{policy.m}")
print(f"Maze:\n{reward.m}")

[[10.1   0.  ]
 [ 1.01  0.  ]]
Epoch: 0
Value:
[[10.1   0.  ]
 [ 1.01  0.  ]]
Policy:
     Down:
[[1. 0.]
 [0. 0.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [1. 0.]]
     Left:
[[0. 1.]
 [0. 1.]]
Policy changes: 2
------------------------------
[[10.1   1.01]
 [ 1.01  0.1 ]]
Epoch: 1
Value:
[[10.1   1.01]
 [ 1.01  0.1 ]]
Policy:
     Down:
[[1. 0.]
 [0. 0.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [1. 1.]]
     Left:
[[0. 1.]
 [0. 0.]]
Policy changes: 1
------------------------------
[[10.1   1.01]
 [ 1.01  0.1 ]]
Epoch: 2
Value:
[[10.1   1.01]
 [ 1.01  0.1 ]]
Policy:
     Down:
[[1. 0.]
 [0. 0.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [1. 1.]]
     Left:
[[0. 1.]
 [0. 0.]]
Policy changes: 0
------------------------------
Final Value:
[[10.1   1.01]
 [ 1.01  0.1 ]]
Final Policy:
[[[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [1. 1.]]

 [[0. 1.]
  [0. 0.]]]
Maze:
[[10.  0.]
 [ 0.  0.]]
