In [1]:
import numpy as np

x, y = 2, 2
a = np.ones((y, x))

In [2]:
a = a * 0
a[(0, 0)] = 10.0
# a[(0, 1)] = 10.0
# a[(1, 0)] = 1.0
a

array([[10.,  0.],
       [ 0.,  0.]])

In [3]:
from greedy_fix import State, Action, Reward, Value, Policy

In [4]:
reward = Reward(a)
value = Value(np.zeros((y, x)), dim=0.1)

In [5]:
"""Create random equiprobable policy"""
# p_m = np.ones((4, y, x))
# p_m = p_m * 0.25
# p_m[:, 0] = 1 / 3
# p_m[:, -1] = 1 / 3
# p_m[:, :, 0] = 1 / 3
# p_m[:, :, -1] = 1 / 3
# p_m[:, 0, 0] = 1 / 2
# p_m[:, 0, -1] = 1 / 2
# p_m[:, -1, 0] = 1 / 2
# p_m[:, -1, -1] = 1 / 2
# p_m[2, 0] = 0.0
# p_m[0, -1] = 0.0
# p_m[3, :, 0] = 0.0
# p_m[1, :, -1] = 0.0
# p_m

'Create random equiprobable policy'

In [6]:
policy_m = np.zeros((4, 2, 2))
policy_m[0] = 1.0
policy_m[0, 1] = 0.0
policy_m[2, 1] = 1.0
print(policy_m)

[[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]


In [7]:
policy = Policy(policy_m)

In [8]:
epochs = 10

In [9]:
np.set_printoptions(precision=2)

for i in range(epochs):
    value.update(policy=policy, reward=reward)
    # Print value
    print(value.m)

    changed = policy.update(value=value, reward=reward)
    # Print Policy
    print(f"Epoch: {i}")
    print(f"Value:\n{value.m}")
    print("Policy:")
    print(f"{' ' * 5}Down:\n{policy.m[0]}")
    print(f"{' ' * 5}Right:\n{policy.m[1]}")
    print(f"{' ' * 5}Up:\n{policy.m[2]}")
    print(f"{' ' * 5}Left:\n{policy.m[3]}")
    print(f"Policy changes: {changed}")
    print('-' * 30)

    if changed == 0:
        break

print(f"Final Value:\n{value.m}")
print(f"Final Policy:\n{policy.m}")
print(f"Maze:\n{reward.m}")

[[ 1.01  0.  ]
 [10.1   0.  ]]
Epoch: 0
Value:
[[ 1.01  0.  ]
 [10.1   0.  ]]
Policy:
     Down:
[[1. 1.]
 [1. 1.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [0. 0.]]
     Left:
[[0. 0.]
 [0. 0.]]
------------------------------
2
[[0. 0.]
 [0. 0.]]
Epoch: 1
Value:
[[0. 0.]
 [0. 0.]]
Policy:
     Down:
[[1. 1.]
 [1. 1.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [0. 0.]]
     Left:
[[0. 0.]
 [0. 0.]]
------------------------------
4
[[0. 0.]
 [0. 0.]]
Epoch: 2
Value:
[[0. 0.]
 [0. 0.]]
Policy:
     Down:
[[1. 1.]
 [1. 1.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [0. 0.]]
     Left:
[[0. 0.]
 [0. 0.]]
------------------------------
4
[[0. 0.]
 [0. 0.]]
Epoch: 3
Value:
[[0. 0.]
 [0. 0.]]
Policy:
     Down:
[[1. 1.]
 [1. 1.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [0. 0.]]
     Left:
[[0. 0.]
 [0. 0.]]
------------------------------
4
[[0. 0.]
 [0. 0.]]
Epoch: 4
Value:
[[0. 0.]
 [0. 0.]]
Policy:
     Down:
[[1. 1.]
 [1. 1.]]
     Right:
[[0. 0.]
 [0. 0.