In [1]:
import numpy as np

a = np.ones((4, 10))

In [2]:
a = a * -1
a[(0, 0)] = 1.0
a[(0, 1)] = 1.0
# a[(1, 0)] = 1.0
a

array([[ 1.,  1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.]])

In [3]:
from greedy import State, Action, Reward, Value, Policy, maze_policy_to_action

In [4]:
reward = Reward(a)
value = Value(np.zeros((4, 10)), dim=1.0)

In [5]:
p_m = np.ones((4, 4, 10))
p_m = p_m * 0.25
p_m[:, 0] = 1 / 3
p_m[:, -1] = 1 / 3
p_m[:, :, 0] = 1 / 3
p_m[:, :, -1] = 1 / 3
p_m[:, 0, 0] = 1 / 2
p_m[:, 0, -1] = 1 / 2
p_m[:, -1, 0] = 1 / 2
p_m[:, -1, -1] = 1 / 2
p_m[2, 0] = 0.0
p_m[0, -1] = 0.0
p_m[3, :, 0] = 0.0
p_m[1, :, -1] = 0.0
p_m

array([[[0.5       , 0.33333333, 0.33333333, 0.33333333, 0.33333333,
         0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.5       ],
        [0.33333333, 0.25      , 0.25      , 0.25      , 0.25      ,
         0.25      , 0.25      , 0.25      , 0.25      , 0.33333333],
        [0.33333333, 0.25      , 0.25      , 0.25      , 0.25      ,
         0.25      , 0.25      , 0.25      , 0.25      , 0.33333333],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        , 0.        , 0.        , 0.        ]],

       [[0.5       , 0.33333333, 0.33333333, 0.33333333, 0.33333333,
         0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.        ],
        [0.33333333, 0.25      , 0.25      , 0.25      , 0.25      ,
         0.25      , 0.25      , 0.25      , 0.25      , 0.        ],
        [0.33333333, 0.25      , 0.25      , 0.25      , 0.25      ,
         0.25      , 0.25      , 0.25      , 0.25      , 0.        ],
        [0.5       , 0.33

In [6]:
policy = Policy(p_m, maze_policy_to_action)

In [7]:
epochs = 10

In [8]:
np.set_printoptions(precision=2)

for i in range(epochs):
    print(value.value_m)
    value.update(policy=policy, reward=reward)
    print(value.value_m)
    policy.greedy_update(value)
    print(f"Epoch: {i}")
    print(f"Value:\n{value.value_m}")
    print("Policy:")
    print(f"{' ' * 5}Down:\n{policy.policy_m[0]}")
    print(f"{' ' * 5}Right:\n{policy.policy_m[1]}")
    print(f"{' ' * 5}Up:\n{policy.policy_m[2]}")
    print(f"{' ' * 5}Left:\n{policy.policy_m[3]}")
    print('-' * 30)
print(f"Final Value:\n{value.value_m}")
print(f"Final Policy:\n{policy.policy_m}")
print(f"Maze:\n{reward.reward_m}")

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[ 0.   -0.33 -0.33 -1.   -1.   -1.   -1.   -1.   -1.   -1.  ]
 [-0.33 -0.5  -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.  ]
 [-1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.  ]
 [-1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.  ]]
Epoch: 0
Value:
[[ 0.   -0.33 -0.33 -1.   -1.   -1.   -1.   -1.   -1.   -1.  ]
 [-0.33 -0.5  -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.  ]
 [-1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.  ]
 [-1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.   -1.  ]]
Policy:
     Down:
[[0.5  0.   0.   0.   0.33 0.33 0.33 0.33 0.33 0.5 ]
 [0.   0.   0.   0.25 0.25 0.25 0.25 0.25 0.25 0.33]
 [0.   0.   0.25 0.25 0.25 0.25 0.25 0.25 0.25 0.33]
 [0.   0.   0.   0.   0.   0.   0.   0.   0.   0.  ]]
     Right:
[[0.5  0.   0.   0.   0.33 0.33 0.33 0.33 0.33 0.  ]
 [0.   0.   0.   0.25 0.25 0.25 0.25 0.25 0.25 0