In [3]:
pip install -U torch


  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
  Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
  Using cached MarkupSafe-2.1.5-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ---------------------------------------- 0.0/199.4 MB ? eta -:--:--
    --------------------------------------- 2.6/199.4 MB 12.5 MB/s eta 0:00:16
    --------------------------------------- 3.7/199.4 MB 12.1 MB/s eta 0:00:17
   - -------------------------------------- 6.3/199.4 MB 9.9 MB/s eta 0:00:20
   - -------------------------------------- 9.4/199.4 MB 11.1 MB/s eta 0:00:18
   -- ------------------------------------- 12.3/199.4 MB 11.7 MB/s eta 0:00:17
   -- ------------------------------------- 14.9/199.4 MB 12.0 MB/s eta 0:00:16
   --- ------------------------------------ 16.3/199.4

In [1]:
import numpy as np

x, y = 2, 2
a = np.ones((y, x))

In [2]:
a = a * 0
a[(0, 0)] = 10.0
# a[(0, 1)] = 10.0
# a[(1, 0)] = 1.0
a

array([[10.,  0.],
       [ 0.,  0.]])

In [3]:
from greedy_fix import State, Action, Reward, Value, Policy

In [4]:
reward = Reward(a)
value = Value(np.zeros((y, x)), dim=0.1)

In [5]:
"""Create random equiprobable policy"""
# p_m = np.ones((4, y, x))
# p_m = p_m * 0.25
# p_m[:, 0] = 1 / 3
# p_m[:, -1] = 1 / 3
# p_m[:, :, 0] = 1 / 3
# p_m[:, :, -1] = 1 / 3
# p_m[:, 0, 0] = 1 / 2
# p_m[:, 0, -1] = 1 / 2
# p_m[:, -1, 0] = 1 / 2
# p_m[:, -1, -1] = 1 / 2
# p_m[2, 0] = 0.0
# p_m[0, -1] = 0.0
# p_m[3, :, 0] = 0.0
# p_m[1, :, -1] = 0.0
# p_m

'Create random equiprobable policy'

In [6]:
"""Create policy go down otherwise go up"""
policy_m = np.zeros((4, y, x))
policy_m[0] = 1.0
policy_m[0, -1] = 0.0
policy_m[2, -1] = 1.0
print(policy_m)

[[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]


In [7]:
policy = Policy(policy_m)

In [8]:
epochs = 1000

In [9]:
np.set_printoptions(precision=2)

for i in range(epochs):
    value.update(policy=policy, reward=reward)
    # Print value
    print(value.m)

    changed = policy.update(value=value, reward=reward)
    # Print Policy
    print(f"Epoch: {i}")
    print(f"Value:\n{value.m}")
    print("Policy:")
    print(f"{' ' * 5}Down:\n{policy.m[0]}")
    print(f"{' ' * 5}Right:\n{policy.m[1]}")
    print(f"{' ' * 5}Up:\n{policy.m[2]}")
    print(f"{' ' * 5}Left:\n{policy.m[3]}")
    print(f"Policy changes: {changed}")
    print('-' * 30)

    if changed == 0:
        break

print(f"Final Value:\n{value.m}")
print(f"Final Policy:\n{policy.m}")
print(f"Maze:\n{reward.m}")

[[10.1   0.  ]
 [ 1.01  0.  ]]
Epoch: 0
Value:
[[10.1   0.  ]
 [ 1.01  0.  ]]
Policy:
     Down:
[[1. 0.]
 [0. 0.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [1. 0.]]
     Left:
[[0. 1.]
 [0. 1.]]
Policy changes: 2
------------------------------
[[10.1   1.01]
 [ 1.01  0.1 ]]
Epoch: 1
Value:
[[10.1   1.01]
 [ 1.01  0.1 ]]
Policy:
     Down:
[[1. 0.]
 [0. 0.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [1. 1.]]
     Left:
[[0. 1.]
 [0. 0.]]
Policy changes: 1
------------------------------
[[10.1   1.01]
 [ 1.01  0.1 ]]
Epoch: 2
Value:
[[10.1   1.01]
 [ 1.01  0.1 ]]
Policy:
     Down:
[[1. 0.]
 [0. 0.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [1. 1.]]
     Left:
[[0. 1.]
 [0. 0.]]
Policy changes: 0
------------------------------
Final Value:
[[10.1   1.01]
 [ 1.01  0.1 ]]
Final Policy:
[[[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [1. 1.]]

 [[0. 1.]
  [0. 0.]]]
Maze:
[[10.  0.]
 [ 0.  0.]]
