In [3]:
pip install -U torch


  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached networkx-3.3-py3-none-any.whl.metadata (5.1 kB)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
  Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
  Using cached MarkupSafe-2.1.5-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
   ---------------------------------------- 0.0/199.4 MB ? eta -:--:--
    --------------------------------------- 2.6/199.4 MB 12.5 MB/s eta 0:00:16
    --------------------------------------- 3.7/199.4 MB 12.1 MB/s eta 0:00:17
   - -------------------------------------- 6.3/199.4 MB 9.9 MB/s eta 0:00:20
   - -------------------------------------- 9.4/199.4 MB 11.1 MB/s eta 0:00:18
   -- ------------------------------------- 12.3/199.4 MB 11.7 MB/s eta 0:00:17
   -- ------------------------------------- 14.9/199.4 MB 12.0 MB/s eta 0:00:16
   --- ------------------------------------ 16.3/199.4

In [7]:
import numpy as np
np.set_printoptions(precision=2)
np.set_printoptions(linewidth=np.inf)

visibility = 2
shape = (10, 10)
map = np.random.rand(*shape) * 100
vis_shape = map.shape
vis_shape = (vis_shape[0] + visibility * 2, vis_shape[1] + visibility * 2)
visibility_map = np.ones(shape=vis_shape, dtype=int) * -1
visibility_map[visibility:-visibility, visibility:-visibility] = map

In [1]:
%pip install torch

  Using cached torch-2.4.1-cp312-cp312-manylinux1_x86_64.whl.metadata (26 kB)
  Using cached filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
  Using cached sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.4.1-py3-none-any.whl.metadata (6.3 kB)
  Using cached jinja2-3.1.4-py3-none-any.whl.metadata (2.6 kB)
  Using cached fsspec-2024.9.0-py3-none-any.whl.metadata (11 kB)
  Using cached setuptools-75.1.0-py3-none-any.whl.metadata (6.9 kB)
  Using cached nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_runtime_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
  Using cached nvidia_cuda_cupti_cu12-12.1.105-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
  Using cached nvidia_cublas_cu12-12.1.3.1-py3-none-manylinux1_x86_64.whl.

In [3]:
l = [[1, 2, 3], [491240, 10]]
s = l[0]
s[1] = 10
print(l)

[[1, 10, 3], [491240, 10]]


In [8]:
import torch

torch.tensor([1, 2, 3])

array([[28.94, 71.09, 69.53, 12.11, 86.57, 61.12, 31.46, 31.98, 28.14,  2.46],
       [ 1.96, 79.75, 99.95, 46.27, 35.79, 93.72, 50.66, 20.46, 10.4 , 38.85],
       [78.75, 26.78, 26.94, 41.66, 63.43, 77.73, 58.65, 21.98, 78.72,  7.95],
       [51.56, 90.23, 38.32, 93.94, 37.68, 70.25, 32.64,  3.38, 43.92,  7.15],
       [ 6.66, 40.52, 96.55, 51.91,  1.77,  1.36, 29.04, 63.27, 37.56, 69.67],
       [17.93,  3.19, 93.98,  4.56, 33.37, 76.47, 13.49, 36.  , 59.97, 50.24],
       [77.43, 84.28, 44.8 , 94.62, 41.09, 58.32, 99.13, 38.96,  6.36, 33.97],
       [61.53, 23.84, 72.  , 88.56, 88.37, 16.78, 69.27, 32.27, 45.66, 49.92],
       [31.3 , 39.2 ,  5.19, 45.29, 41.52, 35.51, 12.23, 33.31, 18.77, 37.21],
       [59.65, 65.33, 64.65, 34.15,  5.29, 24.18, 27.16, 65.55, 85.05, 84.49]])

In [9]:
visibility_map

array([[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, 28, 71, 69, 12, 86, 61, 31, 31, 28,  2, -1, -1],
       [-1, -1,  1, 79, 99, 46, 35, 93, 50, 20, 10, 38, -1, -1],
       [-1, -1, 78, 26, 26, 41, 63, 77, 58, 21, 78,  7, -1, -1],
       [-1, -1, 51, 90, 38, 93, 37, 70, 32,  3, 43,  7, -1, -1],
       [-1, -1,  6, 40, 96, 51,  1,  1, 29, 63, 37, 69, -1, -1],
       [-1, -1, 17,  3, 93,  4, 33, 76, 13, 35, 59, 50, -1, -1],
       [-1, -1, 77, 84, 44, 94, 41, 58, 99, 38,  6, 33, -1, -1],
       [-1, -1, 61, 23, 71, 88, 88, 16, 69, 32, 45, 49, -1, -1],
       [-1, -1, 31, 39,  5, 45, 41, 35, 12, 33, 18, 37, -1, -1],
       [-1, -1, 59, 65, 64, 34,  5, 24, 27, 65, 85, 84, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]])

In [16]:
pos = 0, 0
my_vision = visibility_map[pos[0]:2 * visibility + pos[0] + 1, pos[0]: 2 * visibility + pos[0] + 1]
features = []
for row in my_vision.tolist():
    features += row
print(features, my_vision, sep='\n')

[-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 28, 71, 69, -1, -1, 1, 79, 99, -1, -1, 78, 26, 26]
[[-1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1]
 [-1 -1 28 71 69]
 [-1 -1  1 79 99]
 [-1 -1 78 26 26]]


In [16]:
pos = (0, 0)
visibility = 2
a[min(pos[0] - visibility) : pos[0] + visibility + 1, pos[1] - visibility : pos[1] + visibility + 1]

array([], shape=(0, 0), dtype=float64)

In [17]:
s = np.zeros((10, 12))

In [26]:
### Reward Map tiles meaning
EMPTY = 0
SUBGOAL = -1
GOAL = -2
WALL = -3
# AGENTS = n where n is number of agents on the tile

maze_map = [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
            [1, 0, 1, 0, 0, 0, 1, 0, 0, 1],
            [1, 0, 1, 0, 1, 0, 1, 0, 1, 1],
            [1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
            [1, 1, 1, 0, 1, 1, 1, 1, 0, 1],
            [1, 0, 1, SUBGOAL, 0, 0, 0, 1, 0, 1],
            [1, 0, 0, 0, 1, 1, 0, 0, 0, 1],
            [1, 1, 1, 0, 1, 0, 1, 1, 0, 1],
            [1, 0, 0, 0, 0, 0, 1, GOAL, 0, 1],
            [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

In [6]:
l = [1, 2, 3]
print(l[:None])

[1, 2, 3]


In [20]:
from collections import deque
d = deque([9, 10])
d.append(1)
d.append(2)
print(d)
d.pop()
print(list(d))

deque([9, 10, 1, 2])
[9, 10, 1]


In [8]:
import torch
torch.argmax(torch.tensor([[ 0.1, 0.4, 0.2, 0.8],
        [ 0.9, 0.1, 0.3, 0.5],
        [ 0.2, 0.5, 0.6, 0.4],
        [ 0.7, 0.2, 0.8, 0.1],
        [ 0.3, 0.9, 0.4, 0.1]]), dim=1)

tensor([3, 0, 2, 2, 1])

In [11]:
torch.argmax(torch.tensor([1, 2, 3]))

tensor(2)

In [10]:
print(int(torch.tensor([1, 2, 3])[2]))

3


In [3]:
%pip install torch

Note: you may need to restart the kernel to use updated packages.


In [34]:
s = np.array(maze_map)

s.tolist()

[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
 [1, 0, 1, 0, 0, 0, 1, 0, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0, 1, 1],
 [1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
 [1, 1, 1, 0, 1, 1, 1, 1, 0, 1],
 [1, 0, 1, -1, 0, 0, 0, 1, 0, 1],
 [1, 0, 0, 0, 1, 1, 0, 0, 0, 1],
 [1, 1, 1, 0, 1, 0, 1, 1, 0, 1],
 [1, 0, 0, 0, 0, 0, 1, -2, 0, 1],
 [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]

In [35]:
s = [1, 2, 3, 4, 5, 6, 7, 8]
print(s[:-2])

[1, 2, 3, 4, 5, 6]


In [21]:
[[[] for _ in range(s.shape[1])] for _ in range(s.shape[0])]

[[[], [], [], [], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], [], [], []],
 [[], [], [], [], [], [], [], [], [], [], [], []]]

In [2]:
a = a * 0
a[(0, 0)] = 10.0
# a[(0, 1)] = 10.0
# a[(1, 0)] = 1.0
a

array([[10.,  0.],
       [ 0.,  0.]])

In [3]:
from greedy_fix import State, Action, Reward, Value, Policy

In [4]:
reward = Reward(a)
value = Value(np.zeros((y, x)), dim=0.1)

In [5]:
"""Create random equiprobable policy"""
# p_m = np.ones((4, y, x))
# p_m = p_m * 0.25
# p_m[:, 0] = 1 / 3
# p_m[:, -1] = 1 / 3
# p_m[:, :, 0] = 1 / 3
# p_m[:, :, -1] = 1 / 3
# p_m[:, 0, 0] = 1 / 2
# p_m[:, 0, -1] = 1 / 2
# p_m[:, -1, 0] = 1 / 2
# p_m[:, -1, -1] = 1 / 2
# p_m[2, 0] = 0.0
# p_m[0, -1] = 0.0
# p_m[3, :, 0] = 0.0
# p_m[1, :, -1] = 0.0
# p_m

'Create random equiprobable policy'

In [6]:
"""Create policy go down otherwise go up"""
policy_m = np.zeros((4, y, x))
policy_m[0] = 1.0
policy_m[0, -1] = 0.0
policy_m[2, -1] = 1.0
print(policy_m)

[[[1. 1.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]


In [7]:
policy = Policy(policy_m)

In [8]:
epochs = 1000

In [9]:
np.set_printoptions(precision=2)

for i in range(epochs):
    value.update(policy=policy, reward=reward)
    # Print value
    print(value.m)

    changed = policy.update(value=value, reward=reward)
    # Print Policy
    print(f"Epoch: {i}")
    print(f"Value:\n{value.m}")
    print("Policy:")
    print(f"{' ' * 5}Down:\n{policy.m[0]}")
    print(f"{' ' * 5}Right:\n{policy.m[1]}")
    print(f"{' ' * 5}Up:\n{policy.m[2]}")
    print(f"{' ' * 5}Left:\n{policy.m[3]}")
    print(f"Policy changes: {changed}")
    print('-' * 30)

    if changed == 0:
        break

print(f"Final Value:\n{value.m}")
print(f"Final Policy:\n{policy.m}")
print(f"Maze:\n{reward.m}")

[[10.1   0.  ]
 [ 1.01  0.  ]]
Epoch: 0
Value:
[[10.1   0.  ]
 [ 1.01  0.  ]]
Policy:
     Down:
[[1. 0.]
 [0. 0.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [1. 0.]]
     Left:
[[0. 1.]
 [0. 1.]]
Policy changes: 2
------------------------------
[[10.1   1.01]
 [ 1.01  0.1 ]]
Epoch: 1
Value:
[[10.1   1.01]
 [ 1.01  0.1 ]]
Policy:
     Down:
[[1. 0.]
 [0. 0.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [1. 1.]]
     Left:
[[0. 1.]
 [0. 0.]]
Policy changes: 1
------------------------------
[[10.1   1.01]
 [ 1.01  0.1 ]]
Epoch: 2
Value:
[[10.1   1.01]
 [ 1.01  0.1 ]]
Policy:
     Down:
[[1. 0.]
 [0. 0.]]
     Right:
[[0. 0.]
 [0. 0.]]
     Up:
[[0. 0.]
 [1. 1.]]
     Left:
[[0. 1.]
 [0. 0.]]
Policy changes: 0
------------------------------
Final Value:
[[10.1   1.01]
 [ 1.01  0.1 ]]
Final Policy:
[[[1. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [1. 1.]]

 [[0. 1.]
  [0. 0.]]]
Maze:
[[10.  0.]
 [ 0.  0.]]
